//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecom_Food_Cart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product_image
    {
        public int product_imageId { get; set; }
        public string image_Name { get; set; }
        public string url { get; set; }
        public int productId { get; set; }
    
        public virtual tbl_product tbl_product { get; set; }
    }
}
