//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecom_Food_Cart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_banner
    {
        public int bannerId { get; set; }
        public string banner_Name { get; set; }
        public string url { get; set; }
    }
}
