//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecom_Food_Cart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        public int orderId { get; set; }
        public int customerId { get; set; }
        public int productId { get; set; }
        public decimal order_total { get; set; }
        public System.DateTime order_date { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
        public virtual tbl_product tbl_product { get; set; }
    }
}
